# Generated by Django 5.2.6 on 2025-11-04 15:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Contact name (e.g., Mom, Dad, Brother)', max_length=100)),
                ('phone_number', models.CharField(help_text='Contact phone number', max_length=20)),
                ('relationship', models.CharField(blank=True, help_text='Relationship to user', max_length=50, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary emergency contact')),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emergency Contact',
                'verbose_name_plural': 'Emergency Contacts',
                'ordering': ['-is_primary', 'name'],
                'indexes': [models.Index(fields=['user', 'is_primary'], name='accounts_em_user_id_f07ac5_idx')],
            },
        ),
    ]
