# Generated by Django 5.2.6 on 2025-10-09 13:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('icon_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('details', models.TextField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('Unverified', 'Unverified'), ('Verified', 'Verified'), ('Low confidence', 'Low confidence')], default='Unverified', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Responded', 'Responded'), ('Responding', 'Responding'), ('Resolved', 'Resolved'), ('Dismissed', 'Dismissed')], default='Pending', max_length=20)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('emergency_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergencies.emergencytype')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vote', models.BooleanField(null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergencies.emergencyreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stars', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('did_app_guide_clearly', models.CharField(choices=[('Yes', 'Yes'), ('Somewhat', 'Somewhat'), ('No', 'No')], max_length=20)),
                ('completion_speed', models.CharField(choices=[('Very fast', 'Very fast'), ('Acceptable', 'Acceptable'), ('Too slow', 'Too slow')], max_length=20)),
                ('confidence_level', models.CharField(choices=[('Not confident', 'Not confident'), ('Neutral', 'Neutral'), ('Very confident', 'Very confident')], max_length=20)),
                ('improvement_suggestion', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergencies.emergencyreport')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
