# Generated by Django 5.2.6 on 2025-11-11 15:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0003_alter_image_url_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrowdsourceBroadcast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('recipients', models.ManyToManyField(related_name='crowdsource_broadcasts', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='emergencies.emergencyreport')),
                ('responded_users', models.ManyToManyField(blank=True, related_name='crowdsource_broadcast_responses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
