# Generated by Django 5.2.6 on 2025-11-04 15:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0002_emergencyreport_responder'),
        ('public_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the hotline or organization', max_length=255)),
                ('contact_number', models.CharField(help_text='Contact number', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of services', null=True)),
                ('type', models.CharField(choices=[('Emergency Hotline', 'Emergency Hotline'), ('General Contact', 'General Contact')], default='Emergency Hotline', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Public Hotline',
                'verbose_name_plural': 'Public Hotlines',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='contactredirection',
            options={'verbose_name': 'Hotline Redirection', 'verbose_name_plural': 'Hotline Redirections'},
        ),
        migrations.AlterField(
            model_name='contactredirection',
            name='emergency_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotline_redirections', to='emergencies.emergencytype'),
        ),
        migrations.AddField(
            model_name='contactredirection',
            name='hotline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redirections', to='public_info.hotline'),
        ),
        migrations.AlterUniqueTogether(
            name='contactredirection',
            unique_together={('hotline', 'emergency_type')},
        ),
        migrations.RemoveField(
            model_name='contactredirection',
            name='contact',
        ),
        migrations.DeleteModel(
            name='EmergencyContact',
        ),
    ]
