# Generated by Django 5.2.6 on 2025-11-04 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_info', '0002_hotline_alter_contactredirection_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactredirection',
            name='hotline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirections', to='public_info.hotline'),
        ),
    ]
