# Generated by Django 5.2.6 on 2025-11-11 14:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0003_alter_image_url_fields'),
        ('public_info', '0003_alter_contactredirection_hotline'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Hotline', 'Hotline'), ('General Contact', 'General Contact')], max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='contactredirection',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='contactredirection',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='contactredirection',
            name='emergency_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergencies.emergencytype'),
        ),
        migrations.AddField(
            model_name='contactredirection',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_info.emergencycontact'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='contactredirection',
            name='hotline',
        ),
        migrations.DeleteModel(
            name='Hotline',
        ),
    ]
